# Generated by Django 5.2.8 on 2025-11-23 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividade.cliente'),
        ),
    ]
