# Generated by Django 5.2.8 on 2025-12-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0003_atividade_hora_prevista_alter_atividade_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
