# Generated by Django 5.2.8 on 2025-12-16 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0004_alter_atividade_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
