# Generated by Django 5.2.8 on 2025-12-16 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0005_alter_atividade_valor_alter_atividade_valor_recebido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='arquivo',
            field=models.FileField(upload_to='referencias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
