# Generated by Django 5.2.8 on 2025-12-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0006_alter_referencia_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
