# Generated by Django 5.2.8 on 2026-01-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0007_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='atividade.atividade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='atividade.cliente'),
        ),
    ]
