# Generated by Django 5.2.8 on 2026-02-02 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0008_endereco_atividade_alter_endereco_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='atividades_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
