# Generated by Django 5.2.8 on 2026-02-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0006_role_participante'),
        ('atividade', '0009_atividade_responsaveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='participantes_alocados',
            field=models.ManyToManyField(blank=True, related_name='atividades_alocadas', to='ambiente.participante'),
        ),
    ]
