# Generated by Django 5.2.8 on 2025-12-16 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_user_if_needed(apps, schema_editor):
    """Cria um usuário padrão se necessário e atribui ambientes existentes a ele"""
    User = apps.get_model('auth', 'User')
    Ambiente = apps.get_model('ambiente', 'Ambiente')
    
    # Se não houver usuários, criar um usuário padrão
    if not User.objects.exists():
        user = User.objects.create_user(
            username='admin',
            email='admin@planit.com',
            password='admin123',
            is_staff=True,
            is_superuser=True
        )
    else:
        # Usar o primeiro usuário existente
        user = User.objects.first()
    
    # Atribuir o usuário a todos os ambientes existentes que não têm administrador
    Ambiente.objects.filter(usuario_administrador__isnull=True).update(
        usuario_administrador=user
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='usuario_administrador',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_default_user_if_needed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ambiente',
            name='usuario_administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='usuarios_participantes',
            field=models.ManyToManyField(blank=True, related_name='ambientes_participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
