# Generated by Django 5.2.8 on 2026-01-31 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0003_alter_ambiente_tema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='tema',
            field=models.CharField(blank=True, default='#F26800', help_text='Cor do tema no formato hexadecimal (ex: #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(message='O tema deve ser uma cor no formato #RRGGBB (ex: #FF5733)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
